name: login
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.0.2
  animations: ^2.0.2
  animate_do: ^3.3.4
  cupertino_icons: ^1.0.4
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  flutter_svg: ^2.0.6
  get: ^4.6.6
  google_fonts: ^6.1.0
  google_sign_in: ^6.3.0
  url_launcher: ^6.3.1
  local_auth: ^2.3.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/tec/